### ISSUE TITLE
Incorrect import in rath.turms

### ISSUE THREAD

**Issue by strue36** [jhnnsrs/rath#1]
The example schema imports from rath.turms.operation

This file tries to import `get_current_rath` which no longer exists.

Deleting this import fixes the issue, but does the example schema need to be updated to import the base GraphQL types from the turms package?

**Comment by jhnnsrs** [comment]
i updated the dependencies of rath to the newest version of turms, 

turms will no longer enforce custom base classes that are dependent on itself (so that there is no dependency on a dev dependency) it no uses purely pydantic basemodel.

Also rath comes now included with a custom funcs plugin, that mimics turms operationsfuncplugin:

```yaml
projects:
  default:
    schema: tests/schema.graphql
    documents: graphql/**.graphql
    extensions:
      turms:
        out_dir: tests/api
        stylers:
          - type: turms.stylers.capitalize.Capitalizer
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operation.OperationsPlugin
          - type: rath.turms.plugins.funcs.RathFuncsPlugin
        processors:
          - type: turms.processor.black.BlackProcessor
        scalar_definitions:
          uuid: str
```

Should be working with this repository and generate a new api. There is now a test_turms.py that should help with further tests with generated queries.

Does that work for you now?
